### PR TITLE
feat: `SHVDN2` to `SHVDN3`

### LINKED ISSUE #14: Move to SHVDN3
@CamxxCore please move to SHVDN3 or let someone else manage this repo, kagkin (maintainer of SHVDN) for example

### PR DESCRIPTION
**Pull request by BoBoBaSs84**
chnages:
- quite some

closes #14

### CODE REVIEW

**Comment by BoBoBaSs84** [comment]
@CamxxCore You should really have a close look on this one.

**Review by Probotus — APPROVED** [review]

**Review by CamxxCore — CHANGES_REQUESTED** [review]
Thanks for moving the changes here. Unfortunately I do not have the ability to test these changes in game at the moment, but I see no glaring issues from static analysis. I like the concept with with the code of conduct, however would ultimately like to keep it out of this PR to the the main repo if possible. Thanks for continuing to support this project.

**Comment by BoBoBaSs84** [comment]
@CamxxCore I have removed the `Code of Conduct` from the PR.

**Comment by CamxxCore** [comment]
Thanks for making those changes.

**Pull request merged**
